### ISSUE TITLE
Upgrade code to suitable PHP version 

### ISSUE THREAD

**Issue by Greg0** [kevinpapst/AdminLTEBundle#10]
Hi, I think is good idea to write/rewrite code in/to PHP ^7 with types annotations. Nowadays Symfony 4.1 requires PHP 7.1.
For example class `KevinPapst\AdminLTEBundle\Model\UserInterface` have no documentation and/or return types declared. So without checking usages developer do not know types that methods should return.

I think it is good position to (I supose) already long TODO list :)

I apologize for not being word-perfect in English.
Regards

**Comment by kevinpapst** [comment]
Thanks for the feedback 👍 and yes, you are right, that could be improved.

PRs are very welcome!
