### ISSUE TITLE
Remove test files from git tarballs

### ISSUE THREAD

**Issue by gggeek** [kevinpapst/AdminLTEBundle#104]
It is a good practice to shrink the the 'tarball' version of packages installed via composer as dependencies (ie. the ones installed using `--prefer-dist`), by removing from them those files which are only useful to the developers of said packages themselves (who will either clone the package source code from git or install it as dependency using --prefer-source).

This is easily achieved by adding a .gitattributes file at the root of the project, with lines similar to:
`/Tests export-ignore`

For AdminLTEBundle, the list of excluded files could include:
.github/
.gitignore
.gitattributes
.travis.yml

**Comment by kevinpapst** [comment]
Thanks for your input @gggeek 
There is a good point for removing and a good point for keeping these files. The amount of "noisy" files in this bundle is so small, that the results will likely not matter.
But you can provide a PR and we will see if anyone will comment / leave a 👍 or 👎

**Comment by kevinpapst** [comment]
This was fixed and released a while ago. Closing
