### ISSUE TITLE
NotificationSubscriber

### ISSUE THREAD

**Issue by tooline** [kevinpapst/AdminLTEBundle#108]
Hi,

how i can send the specific route according to notification

$notification
            ->setId(1)
            ->setMessage('A demo message')
            ->setType(Constants::TYPE_SUCCESS)
            ->setIcon('far fa-envelope')
        ;

Thank's

**Comment by kevinpapst** [comment]
You can put arbitrary strings into setId() so use it ... or extend the NotificationModel on your end and add a dedicated method to it.

**Comment by tooline** [comment]
thank's
