### ISSUE TITLE
Menu: method to remove MenuItem

### ISSUE THREAD

**Issue by lduer** [kevinpapst/AdminLTEBundle#111]
I'd like to discuss if it is ok to add a new method `removeItem()` to the [`MenuEvent`-Class](https://github.com/kevinpapst/AdminLTEBundle/blob/master/Event/MenuEvent.php#L64)

Something like this: 
```php

    /**
     * @param MenuItemInterface|MenuItem|string $item
     * @return MenuEvent
     */
    public function removeItem($item)
    {
        if ($item instanceof MenuItemInterface && isset($this->menuRootItems[$item->getIdentifier()])) {
            unset($this->menuRootItems[$item->getIdentifier()]);
        } elseif (is_string($item) && isset($this->menuRootItems[$item])) {
            unset($this->menuRootItems[$item]);
        }

        return $this;
    }
```
With the code from above, one can remove a single MenuItem either by identifier-string or or by passing the object of the item itself.

**Comment by kevinpapst** [comment]
Sounds useful. Seems almost ready, so please go ahead and open a PR.
You just have to add one more clause to check for instanceof KnpMenu\MenuItem.
And please add `: MenuEvent`  as return type to the function declaration.
