### ISSUE TITLE
AdminLTE V3 Block "badge" on template "knp_menu_base.html.twig" does not exist.

### ISSUE THREAD

**Issue by tooline** [kevinpapst/AdminLTEBundle#126]
Hello when I use KnpMenuBuilderSubscriber AdminLTE V3, I get this error message 👍 ( 
I don't want to use the badge )

![image](https://user-images.githubusercontent.com/22789071/79607001-c5f79700-80f2-11ea-80cf-12220320cb04.png)

>     private function addToMenu($module, ItemInterface $menu, KnpMenuEvent $event): void
>     {
>         $children = $this->repository->getRepositoryMenu()->findByParentId($module->getId());
>         if (count($children) > 0) {
>             $options = [
>                 'label' => $module->getTitleCode(),
>                 'childOptions' => $event->getChildOptions(),
>                 'options' => [
>                     'branch_class' => 'treeview',
>                 ]
>             ];
>         } else {
>             $options = [
>                 'route' => $module->getRoute(),
>                 'label' => $module->getTitleCode(),
>                 'childOptions' => $event->getChildOptions()
>             ];
>         }
>         $newMenu = $menu->addChild($module->getId(), $options)
>                         ->setLabelAttribute('icon', $module->getFaIcon());
>         foreach ($children as $child) {
>             $this->addToMenu($child, $newMenu, $event);
>         }
>     }
>     /**
>      * Generate the main menu.
>      *
>      * @param KnpMenuEvent $event
>      */
>     public function onSetupMenu(KnpMenuEvent $event)
>     {
>         $menu = $event->getMenu();
> 
>         $menus = $this->repository->getRepositoryMenu()->findAllParentActif();
> 
>         $menu->addChild(
>             'menu-label',
>             ['label' => 'menu.main', 'childOptions' => $event->getChildOptions()]
>         )->setAttribute('class', 'header');
> 
>         foreach ($menus as $module) {
>             $this->addToMenu($module, $menu, $event);
>         }
> 
>         $menu->addChild('logout', ['route' => 'security_logout', 'label' => 'menu.logout', 'childOptions' => $event->getChildOptions()])->setLabelAttribute('icon', 'fas fa-sign-out-alt');
>     }

Thanks

**Comment by kevinpapst** [comment]
I am not sure what you mean. Are you trying the v3 branch from #109 ?
If so, this is obviously not ready yet.
But you can share your findings and open a PR to fix it!

**Comment by tooline** [comment]
Ok thank you very much i will try
