### ISSUE TITLE
ChoiceType expanded doesn't translate choices properly

### ISSUE THREAD

**Issue by curtchan** [kevinpapst/AdminLTEBundle#127]
> {# form-theme-base.html.twig | AdminLTE Bundle #}
> {% block choice_widget_expanded %}
>     {% apply spaceless %}
>         <div {{ block('widget_container_attributes') }}>
>             {% for child in form %}
>                 {{ form_widget(child) }}
>             {% endfor %}
>         </div>
>     {% endapply %}
> {% endblock choice_widget_expanded %}

> {# bootstrap_base_layout.html.twig #}
> {% block choice_widget_expanded -%}
>     {%- if '-inline' in label_attr.class|default('') -%}
>         {%- for child in form %}
>             {{- form_widget(child, {
>                 parent_label_class: label_attr.class|default(''),
>                 translation_domain: choice_translation_domain,
>             }) -}}
>         {% endfor -%}
>     {%- else -%}
>         <div {{ block('widget_container_attributes') }}>
>             {%- for child in form %}
>                 {{- form_widget(child, {
>                     parent_label_class: label_attr.class|default(''),
>                     translation_domain: choice_translation_domain,
>                 }) -}}
>             {%- endfor -%}
>         </div>
>     {%- endif -%}
> {%- endblock choice_widget_expanded %}

Apparently it doesn't properly pass the choice_translation_domain property down to choices

**Comment by kevinpapst** [comment]
Ok, never appeared to me. Maybe because I am always using the default "messages" namespace for forms.

Can you file a PR to fix it?

**Comment by curtchan** [comment]
Why does this bundle force it's own theme first of all? Using Symfony's built-in bootstrap_3_layout.html.twig or bootstrap_4_layout.html.twig should be enough?

**Comment by kevinpapst** [comment]
You can deactivate it: https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/form_theme.md

**Comment by curtchan** [comment]
Thanks for point option for deactivating it, i missed it when checking docs, but still, i can't see any difference between bootstrap_3 and the custom theme provided by this bundle, is it really worth supporting it? Maybe extending the bootstrap_3(_horizontal) and overriding just few blocks would be enough (depending on what is actually overridden by bundle)

**Comment by kevinpapst** [comment]
It just overwrites [some parts of the bootstrap_3  theme](https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/views/layout/form-theme-base.html.twig#L1), but don't ask me why... I simply can't remember 😁

**Comment by curtchan** [comment]
Oh, indeed, by some reason i was sure it overrides div_layout. I see that it overrides some form types to add icon prefix for inputs, maybe someone just overlooked expanded choice widget when overriding it 👍

**Comment by kevinpapst** [comment]
Can you file a PR for that @curtchan ?

**Comment by kevinpapst** [comment]
Seems nobody cares, closing
