### ISSUE TITLE
Nested Child Items in KNP Menu

### ISSUE THREAD

**Issue by tacman** [kevinpapst/AdminLTEBundle#128]
I'm defining the sidebar using KnpMenu 

```php
    public function createAdminMenu(array $options)
    {
        $menu = $this->factory->createItem('root')
            ->setExtra('translation_domain', true)
        ;

        $publicMenu = $menu->addChild('public', ['attributes' => ['collapse' => true]]);
        $publicMenu->addChild('public_surveys',
            ['route' => 'survey_index'])->setAttribute('icon', 'fas fa-home');
        $publicMenu->addChild('survos_landing', ['route' => 'app_homepage'])->setAttribute('icon', 'fas fa-home');

        $surveyMenu = $menu->addChild('survey.menu');
        $surveyMenu->addChild('survey.new', ['route' => 'survey_new']);
        $surveyMenu->addChild('survey.list', ['route' => 'survey_index']);
```

It's rendering the top items, with the chevron, but is not opening.  The menu items are in the DOM, but hidden:

![image](https://user-images.githubusercontent.com/619585/80506536-ba526e80-8943-11ea-83e4-07432de37ec1.png)

I imagine something isn't being configured correctly, do I need to add an attribute or a class for it to properly open?  Or call a javascript function?  Or a css file?

**Comment by kevinpapst** [comment]
Please check the demo app: 
https://github.com/kevinpapst/AdminLTEBundle-Demo/blob/master/src/EventSubscriber/KnpMenuBuilderSubscriber.php#L50

**Comment by tacman** [comment]
My menus have been set up as a service:

https://symfony.com/doc/master/bundles/KnpMenuBundle/menu_builder_service.html

As such, I don't have access to the $event object.  Is it necessary to switch to an Event Listener, or can the child menus be rendered using a service?  I assume it's the 'childOptions' property that I'm missing:

    'childOptions' => $event->getChildOptions()

Thanks.

**Comment by kevinpapst** [comment]
I never used KNP Menu, so I cannot help with that question. 
But if you can share your solution, it will help the next user 😄

**Comment by tacman** [comment]
I think I'm getting closer, the menu appears to be rendering with the right classes:

```php
    public function createAdminMenu(array $options)
    {
        $menu = $this->factory->createItem('root')
            ->setExtra('translation_domain', true)
        ;

        $childOptions = [
            'attributes' => ['class' => 'treeview'],
            'childrenAttributes' => ['class' => 'treeview-item'],
            'labelAttributes' => []
        ];

        $publicMenu = $menu->addChild('public', [
            'childOptions' => $childOptions,
        ]);
        $publicMenu->addChild('public_surveys',
            [
                'childOptions' => $childOptions,
                'route' => 'survey_index'])
            ->setAttribute('icon', 'fas fa-home');

        $publicMenu->addChild('survos_landing', [
            'childOptions' => $childOptions,
            'route' => 'app_homepage'])
            ->setAttribute('icon', 'fas fa-home');

        return $menu;
```

But the styling doesn't look right, so I'm thinking that maybe the js isn't right either.  It looks like they're code for handling treeview in adminlte.js, so maybe I'm not calling that right?

My base layout extends the recommended base, since I'm also using encore I use a script and link tag to get my files:


```twig
{% extends '@AdminLTE/layout/default-layout.html.twig' %}

    {% block stylesheets %}
        {# reversed, ugh.   #}
        {{ encore_entry_link_tags('app') }}
        {{ parent() }}
    {% endblock %}

    {% block javascripts %}
        {{ parent() }}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}

{% block page_content %}
    {{ block('body') }}
{% endblock %}
```

**Comment by tacman** [comment]
Should I somehow be configuring adminlte files in _my_ webpack.config.js?

**Comment by kevinpapst** [comment]
If you build your assets, then include the adminlte sources as well and don't use the pre-built ones.

Thats in the demo app as well:
https://github.com/kevinpapst/AdminLTEBundle-Demo/blob/master/webpack.config.js
https://github.com/kevinpapst/AdminLTEBundle-Demo/blob/master/assets/adminlte-demo.js

Base layout has no own encore asset tags:
https://github.com/kevinpapst/AdminLTEBundle-Demo/blob/master/templates/base.html.twig

**Comment by tacman** [comment]
I'm close, but I think there's an issue with where the demo assets are being published.
```bash
git clone https://github.com/survos/formeo-demo.git demo && cd demo && composer install 
yarn install && yarn run encore dev
```
Encore fails because of the admin-lte css file, and I'm not sure how to fix the reference to it.

Can you install my project (it's pretty small, mostly a demo of a bunch of great tools) and guide me how the admin css and js are supposed to be integrated?  I'll update the documentation then if appropriate.

Thanks.

**Comment by tacman** [comment]
I thought 

    yarn add admin-lte

might help, but it didn't.  It seems like the .js file is referencing admin-lte, but without a relative path.

Perhaps I'm confused about the JS libraries v. the AdminLte bundle?

**Comment by kevinpapst** [comment]
If you require `"admin-lte": "^2.4",` with yarn, you can try to use the original sources from node_modules via:
```
require('admin-lte/dist/css/AdminLTE.min.css');
require('admin-lte/dist/css/skins/_all-skins.css');
require('../vendor/kevinpapst/adminlte-bundle/Resources/assets/admin-lte-extensions.scss');
global.$.AdminLTE = {};
global.$.AdminLTE.options = {};
require('admin-lte/dist/js/adminlte.min');
```

**Comment by tacman** [comment]
I've installed 2.4 as you've suggested, but anything that references admin-lte, such as

```javascript
require('admin-lte/dist/css/AdminLTE.css');
```

gives an error:

```
TypeError: modules[moduleId] is undefined
bootstrap:89
    Webpack 7
```

The files themselves are there.  
​

**Comment by kevinpapst** [comment]
And why do you think this error is related to AdminLTE?

**Comment by tacman** [comment]
KNP Menu simply generates the HTML, which appears to be correct.  But the javascript isn't working.

One possibility is that the AdminLTE jQuery object is not the same as the jQuery object that the application uses.   My code contains this ugliness in app.js, and while encore doesn't throw any errors, I'm not at all confident that this is correct.

 
```javascript
const $ = require('jquery');
require('bootstrap');
global.$ = $;

require('admin-lte/dist/css/AdminLTE.min.css');
require('admin-lte/dist/css/skins/_all-skins.css');
require('../../vendor/kevinpapst/adminlte-bundle/Resources/assets/admin-lte.scss');
require('../../vendor/kevinpapst/adminlte-bundle/Resources/assets/admin-lte-extensions.scss');
global.jQuery = $;
global.$.AdminLTE = {};
global.$.AdminLTE.options = {};
require('admin-lte/dist/js/adminlte.min');
```

Or perhaps this would work better with 'import' instead of 'require'?  I'm no javascript expert by any means, so it's likely I'm doing something wrong.

Code is available here: https://github.com/survos/formeo-demo
Demo is here: https://formeo-demo.herokuapp.com/

**Comment by kevinpapst** [comment]
I am not an JS expert as well. 

The README contains links to two applications, the demo app and Kimai - both of them use the Admin LTE theme and there are hundreds of other users who are using AdminLTE without problem. 

Debugging your app can only be done by yourself.

The only hint I can give you is the same that always applies: remove everything that is not required for the test case (here the javascript and style blocks / your own asset builds) and try if it works with the default assets. 

If so, add one piece after another to find out when it breaks.

Did you run the demo app with KNP menu? Switch this to true:
https://github.com/kevinpapst/AdminLTEBundle-Demo/blob/master/config/packages/admint_lte.yaml#L41
and compare the resulting HTML with yours

**Comment by tacman** [comment]
I think I've figured it out, or at least made some progress.  The short answer is "no", it appears that you can't use MenuBuilder as a service, but it works great if you use it as a listener as you've done in the demos.

Thanks, I'll fix my app and publish it shortly, with some instructions on how to easily integrate this terrific bundle.

**Comment by kevinpapst** [comment]
Looking forward!

**Comment by tacman** [comment]
I'll close this, even though there probably _is_ a way to use a MenuBuilder service.  I was unfamiliar with using events to build the menu, but now that I understand it I'll simple leave a comment on how to do so.

```bash
bin/console make:subscriber XMenuSubscriber "KevinPapst\AdminLTEBundle\Event\KnpMenuEvent"
```

Then simple grab the menu from the event handler and start adding items:

```php
    public function onKnpMenuEvent(KnpMenuEvent $event)
    {
        $menu = $event->getMenu();
        $menu->addChild('google', ['uri' => 'http://google.com']);
        // ...
    }
```
