### ISSUE TITLE
How control adding "*" for label?

### ISSUE THREAD

**Issue by nickicool** [kevinpapst/AdminLTEBundle#13]
I just install bundle. This is very useful library, good work! But how control adding "*" for each label field? I find some code in your bundle
   
    {% block form_label %}
    {{ parent() }}
    {% if required and label is not same as (false) %}
        <sup class="required" title="{{ "This is a mandatory field"|trans({}, translation_domain) }}">
            <i class="fas fa-asterisk"></i>
        </sup>
    {% endif %}
    {% endblock form_label %}

How can I disable the output of this information for some form fields?

**Comment by kevinpapst** [comment]
Hi!
The output of this depends on your form. If the form field/type is required, then this will sho up.
Either define form type as optional (required=false) or the label to false:
```
        $builder
            ->add('name', TextType::class, [
                'label' => false,
                'required' => false,
            ])
```

**Comment by nickicool** [comment]
Thank you my friend! This bundle is very usfull!
