### ISSUE TITLE
Add Request to KnpMenuEvent

### ISSUE THREAD

**Issue by tacman** [kevinpapst/AdminLTEBundle#133]
The MenuEvent class contains the request, but KnpMenuEvent does not.  Having the request there would be helpful for customizing the menu based on route.

I can add a PR for this if that makes sense, I think it's simply adding the request to the constructor if you think this is a good idea.

**Comment by kevinpapst** [comment]
I don't think the event should be in the request, thats already a "failure".

Simply fetch the request from the RequestStack in your Subscriber/Listener.
```php
    public function __construct(RequestStack $requestStack)
    {
        $this->request = $requestStack->getCurrentRequest();
    }
```

**Comment by tacman** [comment]
But it's in the constructor of the other MenuEvent, along with a
getRequest().  Are you saying you think it shouldn't be there?  Is that
what you mean by 'failure'.  If so, maybe mark getRequest as deprecated?
