### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by darthf1** [kevinpapst/AdminLTEBundle#14]
Hi. I just installed your bundle (thanks for making an updated fork!). I got an error when running `encore production` and i am unsure how to proceed. I copied the `package.json` from your bundle to my app.
```
./node_modules/.bin/encore production
Running webpack ...
ERROR  Failed to compile with 1 errors                               1:18:43 PM
This dependency was not found:
* admin-lte/dist/js/app.min in ./vendor/kevinpapst/adminlte-bundle/Resources/assets/admin-lte.js
To install it, you can run: npm install --save admin-lte/dist/js/app.min
```
Should i just run `yarn install --save admin-lte/dist/js/app.min` or is something else missing?

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 4.1.3  |
| Operating System  | Ubuntu 18.04 |

**Comment by kevinpapst** [comment]
Please compare your installation with the Demo installation/implementation:
https://github.com/kevinpapst/AdminLTEBundle-Demo

I guess you just mixed up the directories, how does your main js file look like?
Compare to this: https://github.com/kevinpapst/AdminLTEBundle-Demo/blob/master/assets/adminlte-demo.js

Did you reference the vendor file correctly?

**Comment by kevinpapst** [comment]
Or, maybe I misread the error message... did you execute `yarn install` as described here:
https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/extend_webpack_encore.md

**Comment by darthf1** [comment]
In my `main.js` I have:
`require('../../vendor/kevinpapst/adminlte-bundle/Resources/assets/admin-lte');`

In de Demo applications you go back 1 directory:
https://github.com/kevinpapst/AdminLTEBundle-Demo/blob/master/assets/adminlte-demo.js
This gives me the following error:
```
./node_modules/.bin/encore production
Running webpack ...
ERROR  Failed to compile with 1 errors                               5:10:31 PM
This relative module was not found:
* ../vendor/kevinpapst/adminlte-bundle/Resources/assets/admin-lte in ./assets/js/app.js
```

In the Extend Webpack Encore you go back 2 directories, so thats the one im having at the moment. For the rest of the installation i followed the exact page.
https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/extend_webpack_encore.md

```
/assets/js/app.js
require('../vendor/kevinpapst/adminlte-bundle/Resources/assets/admin-lte');
```
```
/webpack.config.js
var Encore = require('@symfony/webpack-encore');
Encore
    .setOutputPath('public/builds/')
    .setPublicPath('/builds')

    // this will be your app!
    .addEntry('app', './assets/js/app.js')
    .autoProvidejQuery()
    .enableSourceMaps(!Encore.isProduction())
    .cleanupOutputBeforeBuild()
    .enableBuildNotifications()
    .enableSassLoader()
;
module.exports = Encore.getWebpackConfig();
```
```
/package.json
{
    "devDependencies": {
        "@fortawesome/fontawesome-free": "~5.1.1",
        "@symfony/webpack-encore": "^0.20.1",
        "admin-lte": "~2.4.8",
        "bootstrap-sass": "^3.3.7",
        "bootstrap-select": "^1.13.1",
        "chart.js": "1.1.*",
        "daterangepicker": "^3.0.3",
        "icheck": "^1.0.2",
        "jquery": "^3.3.1",
        "jquery-slimscroll": "^1.3.8",
        "jquery-ui": "^1.12.1",
        "js-cookie": "^2.2.0",
        "node-sass": "^4.9.0",
        "sass-loader": "^7.0.2",
        "webpack-notifier": "^1.5.1"
    },
    "license": "UNLICENSED",
    "private": true,
    "scripts": {
        "dev-server": "encore dev-server",
        "dev": "encore dev",
        "watch": "encore dev --watch",
        "build": "encore production"
    },
    "dependencies": {}
}
```

**Comment by kevinpapst** [comment]
At the first glimpse I cannot spot the difference.
Can you check your the `vendor/kevinpapst/adminlte-bundle/...` directory, is the file existing?
What in your composer.json? And how did you install the bundle?

You can also compare it with this repository: https://github.com/kevinpapst/kimai2
I am using this bundle there as well.

And I use the same path setup `assets/js/app.js` there as you do, compare https://github.com/kevinpapst/kimai2/blob/master/assets/js/app.js

**Comment by darthf1** [comment]
Despite the error I do not have an issue with the bundle/theme so far. The file in the directory is existing as well.
/composer.json:
```
    "require": {
        "php": "^7.2",
        "ext-amqp": "*",
        "ext-bcmath": "*",
        "ext-ctype": "*",
        "ext-curl": "*",
        "ext-gmp": "*",
        "ext-iconv": "*",
        "ext-json": "*",
        "ext-pdo_mysql": "*",
        "doctrine/orm": "2.7.x-dev@dev",
        "kevinpapst/adminlte-bundle": "^1.1",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/asset": "^4.0",
        "symfony/console": "^4.0",
        "symfony/dotenv": "^4.0",
        "symfony/filesystem": "^4.0",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^4.0",
        "symfony/lock": "^4.0",
        "symfony/lts": "^4@dev",
        "symfony/maker-bundle": "^1.0",
        "symfony/messenger": "^4.0",
        "symfony/monolog-bundle": "^3.2",
        "symfony/orm-pack": "^1.0",
        "symfony/security-bundle": "^4.0",
        "symfony/serializer-pack": "^1.0",
        "symfony/stopwatch": "^4.0",
        "symfony/twig-bundle": "^4.0",
        "symfony/web-server-bundle": "^4.0",
        "symfony/webpack-encore-pack": "^1.0",
        "symfony/yaml": "^4.0"
    },
```
I installed the bundle using Flex
```
composer config extra.symfony.allow-contrib true
composer req "kevinpapst/adminlte-bundle:^1.1"
```

**Comment by kevinpapst** [comment]
Okay, I finally see whats wrong here...

There was a bug in packages.json related to the required version which was fixed with  [this commit](https://github.com/kevinpapst/AdminLTEBundle/commit/e9ba0374f1cb952d9c987b5d2f2fd78274c8d3dd#diff-f76dd3d0d2cc93e5857afcaeeb12e068). 

But your are already using the packages.json from the master, pointing to the latest admin-lte in version 2.4.8, but still using the bundle in version 1.2.

The support for AdminLTE 2.4.8 was not yet released, its in master and the release is prepared in  #17.

So you either need to point your composer.json to dev-master of this bundle or you switch back to admin-lte 2.3.11 for the meantime, until I release 2.0 of this bundle with full support for AdminLTE 2.4.8.

You can see what you installed with `yarn list admin-lte` and check the missing files with `ls -la node_modules/admin-lte/dist/js/`.

**Comment by darthf1** [comment]
Yes that resolves it! Thanks.
