### ISSUE TITLE
Movable widget in dashboard

### ISSUE THREAD

**Issue by evskorobogatij** [kevinpapst/AdminLTEBundle#145]
Hi.

I uses dev-adminlte-v3 and symfony 5
In sample page of adminlte3 https://adminlte.io/themes/v3/index.html user can move widgets by drag and drop

I what realise this behavior to users in my projects 

```html

  <div class="row">

        <section class="col-md-4 connectedSortable ui-sortable">
            <div class="card card-primary">
                 <div class="card-header with-border ui-sortable-handle " style="cursor: move">
                   .....
                 </div>
               ...
            </div>
              ....
        </div>

        <section class="col-md-4 connectedSortable ui-sortable">
                 .....
        </div>

        <section class="col-md-4 connectedSortable ui-sortable">
             .....
        </div>

<div>

```

Cursor changed? but widgets not dragged

I miss include some js? 

How release this?
How restore widget position after page refresh

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 5.1  |
| AdminLTEBundle  | dev-adminlte-v3  |
| Operating System  | Windows  |

**Comment by kevinpapst** [comment]
This feature is not in the scope of the bundle by now. 
If you want to provide a PR with the necessary changes, I will happily review it.
