### ISSUE TITLE
Symfony 5.1 error open route `fos_user_registration_register`

### ISSUE THREAD

**Issue by nickicool** [kevinpapst/AdminLTEBundle#146]
Hi friend!

Can you help me pls? I upgrade my project from SF 4.3 -> 5.1.2. All works, but if open route `fos_user_registration_register` I get error:

`
Argument 1 passed to Symfony\Bridge\Twig\Extension\TranslationExtension::trans() must be of the type string, null given, called in D:\OpenServer\domains\symfony-5.local\var\cache\dev\twig64\647eb71b189054611b2a433b105614b34e272fd4c886d6282b73484df352de91.php on line 71
`
![2020-07-07_00-36-43](https://user-images.githubusercontent.com/20491990/86648978-024bdc80-bfea-11ea-88f2-9eb5e78e0dd1.png)

I'm not very experienced, and I don't know where to look for the problem. Can you do anything to help?

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 5.1.2  |
| AdminLTEBundle  | ^3.2  |
| Operating System  | Windows  |

**Comment by kevinpapst** [comment]
See #148
