### ISSUE TITLE
Error if themed by form-theme-security.html.twig

### ISSUE THREAD

**Issue by evskorobogatij** [kevinpapst/AdminLTEBundle#148]
Hi.

I use adminlte in my project.

I build registration form with '@AdminLTE/layout/security-layout.html.twig'
```twig
{% extends '@AdminLTE/layout/security-layout.html.twig' %}

{% block login_social_auth %}{% endblock %}

{% block login_box_msg %}
    {{ 'Register a new account' }}
{% endblock %}

{% block login_form %}

    {% form_theme registrationForm '@AdminLTE/layout/form-theme-security.html.twig' %}

    {{ form_start(registrationForm) }}
    {{ form_widget(registrationForm) }}
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block">{{ 'registration.submit' }}</button>
    </div>
    {{ form_end(registrationForm) }}

{% endblock %}

{% block login_actions %}
    <br>
    <a href="{{ path('adminlte_login'|route_alias) }}">
        {{ 'Back to login' }}
    </a>
{% endblock %}
```

In controller I render this form? but its an error occured:
```Argument 1 passed to Symfony\Bridge\Twig\Extension\TranslationExtension::trans() must be of the type string, null given, called in .... ```

How to fix this?

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | Your current symfony version  |
| AdminLTEBundle  | dev-adminlte-v3  |
| Operating System  | Windows  |

**Comment by kevinpapst** [comment]
Same as #146 - must be a change in FOSUserBundle oder Symfony 5. 

As there is no `|trans` filter called in your code, I would guess it is this line:
https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/views/layout/security-layout.html.twig#L29

Remove it and test with `{{ dump(error) }}`

**Comment by nickicool** [comment]
I tried to comment on this line, but there is no effect...

**Comment by evskorobogatij** [comment]
> 
> 
> Same as #146 - must be a change in FOSUserBundle oder Symfony 5.
> 
> As there is no `|trans` filter called in your code, I would guess it is this line:
> https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/views/layout/security-layout.html.twig#L29
> 
> Remove it and test with `{{ dump(error) }}`

I don't use FOSUserBundle . 
I have entity User for storing user data and RegistrationForm, created with make:registration-form

**Comment by kevinpapst** [comment]
What about you @nickicool ?

I have actually never tested it without FOSUserBundle.

**Comment by evskorobogatij** [comment]
I replace 
```twig
{#    {% form_theme registrationForm '@AdminLTE/layout/form-theme-security.html.twig' %}#}
        {% form_theme registrationForm '@AdminLTE/layout/form-theme-base.html.twig' %}
```
And then customize inpunts look

**Comment by nickicool** [comment]
I'm still using FOSUserBundle, and here's what I found. In the view folder, I have a FOSUserBundle folder, with few files for very small customize (just hide logo):

![2020-07-09_13-34-33](https://user-images.githubusercontent.com/20491990/87029702-2c1f2200-c1e9-11ea-9f1a-366ea39cff69.png)

For example:

    // templates\bundles\FOSUserBundle\Registration\register.html.twig
    {% extends '@AdminLTE/FOSUserBundle/Registration/register.html.twig' %}
    {% block logo_login %}{% endblock %}

    // templates\bundles\FOSUserBundle\Security\login.html.twig
    {% extends '@AdminLTE/FOSUserBundle/Security/login.html.twig' %}
    {% block logo_login %}{% endblock %}

Now `login` and `resetting` work well, `register` with error. But, if just rename/delete folder `templates\bundles\FOSUserBundle`:
- all routs open without errors, but and without any styles.
- 'login' form without links `Registration of users`, `I forgot my password`.

![2020-07-09_14-06-11](https://user-images.githubusercontent.com/20491990/87032498-64286400-c1ed-11ea-9acf-691e2bd50dbd.png)
![2020-07-09_14-07-32](https://user-images.githubusercontent.com/20491990/87032618-90dc7b80-c1ed-11ea-9987-a3323acbca74.png)

And I'm use Twig 2.13.0 (with 3.x FOSUserBundle refuses to install). May be this important.

**Comment by kevinpapst** [comment]
Please find out the offending line.
If there error says `Argument 1 passed to Symfony\Bridge\Twig\Extension\TranslationExtension::trans() must be of the type string, null given, called in ...` then open that file and check the line.
It is the compiled twig template, which should give you a hint what to search for in your template.
Maybe it is the underlying form theme that has updates like a missing label

**Comment by nickicool** [comment]
Hi!

I tried to find the string that causes the error. It turned out to be `{% set attr = attr|merge({'placeholder': label|trans({}, translation_domain)}) %}` (line 4 in `\vendor\kevinpapst\adminlte-bundle\Resources\views\layout\form-theme-security.html.twig`). 

For fix this i change line to `{% set attr = attr|merge({'placeholder': label|default('')|trans({}, translation_domain)}) %}`

@kevinpapst you will be able to release a fixed version?

**Comment by kevinpapst** [comment]
LOL, it was really a missing label? That was a lucky guess. Nice debugging work, thanks @nickicool !

I wonder if it wouldn't be better to add a check like
```
{% if label is defined and label is not null and label is not same as (false) %}
```
to prevent an empty placeholder attribute or some other unwanted behavior due to the translation of the empty string `''|trans`.

Can you open a PR, then I will merge and release a bugfix release.
