### ISSUE TITLE
Impossible to access an attribute ("started") on a null variable.

### ISSUE THREAD

**Issue by darthf1** [kevinpapst/AdminLTEBundle#15]
After installation I navigated to the dashboard index and received the following Twig error:
`Impossible to access an attribute ("started") on a null variable.`

After inspection it seems that the `app.session` variable (which is called in the flash messages partial) is `null`. How can I set this variable correctly?

I dont know whether it belongs here in this tracker or if its a generic thing related to Symfony. 

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 4.1.3  |
| Operating System  | Ubuntu 18.04  |

**Comment by darthf1** [comment]
Ignore this one. 

https://symfony.com/doc/current/controller.html#managing-the-session

**Comment by kevinpapst** [comment]
Thats an interesting finding. 
I never tested without session enabled. But I think that can be easily fixed, so I reopen the ticket.
