### ISSUE TITLE
need to bump frontend dependencies and rebuild assets ?

### ISSUE THREAD

**Issue by gggeek** [kevinpapst/AdminLTEBundle#150]
Hello

I updated an app to adminlte-bundle 3.2.4 today, and when pushing the yarn.lock file as part of my repo, github complained about security problems in the currently used versions of 8 js packages.

I am not 100% sure about how to best fix that:
a. run a yarn/webpack update within my app ?
b. clone adminlte-bundle, run a yarn/webpack update in it and submit a PR ?
c. something else ?

In case of A or B, which would be the exact commands to run: `yarn upgrade`? `./node_modules/.bin/encore` ?

Also: is it correct to assume that, although the final app runs on php without node.js, an insecure js dependency in in yarn.lock could end up packaged in the js files served by the app, and thus affect end users? Or, viceversa, are all the yarn js dependencies only used at app 'build time' and thus not really a big issue?

(pardon my ignorance, I dabble with frontend tech very rarely...)

**Comment by kevinpapst** [comment]
I can't release a new version for each new security warning that pops up every second day.

You should manage your frontend dependencies by yourself.
Use `yarn install --force` and then `encore production` to rebuild them.
