### ISSUE TITLE
symfony/asset is a dependancy, but not added to this projects dependancies

### ISSUE THREAD

**Issue by tommym9** [kevinpapst/AdminLTEBundle#151]
On initial install I set up a template to extend from the default layout `{% extends '@AdminLTE/layout/default-layout.html.twig' %}`, but I got an error about `symfony/asset`.

Looking in the default layout there is a call to asset(), but I don't have this installed.

My solution would be to either:

* Add `symfony/asset` as a dependancy to this package
* Remove calls to asset to break the dependancy

Not a huge issue for me as I added `symfony/asset` to my project.

Cheers

Tom

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 5.1.3  |
| AdminLTEBundle  | 3.2.4  |
| Operating System  | Ubuntu  |

**Comment by kevinpapst** [comment]
Thanks for the heads up @tommym9 - I'll have a look into it
