### ISSUE TITLE
NotificationSubscriber not show if not auth

### ISSUE THREAD

**Issue by Grazulex** [kevinpapst/AdminLTEBundle#153]
Hello,

I have install and follow the instructions to used this projet. Everything is ok but I have a issue with the subscriber (task, notification and message).
When the user is not logged, we don't have any user widget in the menu and this is right. but I don't find the way to do the same with the task, notification and message one.

I have put a control but nothing to do, we have always the 3 items in the menu..the counter are on O but I don't find the way to NOT show these 3 items when the user is not logging.

` <?php

/*
 * This file is part of the AdminLTE-Bundle demo.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\EventSubscriber;

use KevinPapst\AdminLTEBundle\Event\NotificationListEvent;
use KevinPapst\AdminLTEBundle\Helper\Constants;
use KevinPapst\AdminLTEBundle\Model\NotificationModel;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

/**
 * Class NotificationSubscriber adds notification messages to the top bar.
 */
class NotificationSubscriber implements EventSubscriberInterface
{
    /**
     * @var AuthorizationCheckerInterface
     */
    private $security;

    /**
     * @param AuthorizationCheckerInterface $security
     */
    public function __construct(AuthorizationCheckerInterface $security)
    {
        $this->security = $security;
    }

    /**
     * @return array
     */
    public static function getSubscribedEvents(): array
    {
        return [
            NotificationListEvent::class => ['onNotifications', 100],
        ];
    }

    /**
     * @param NotificationListEvent $event
     */
    public function onNotifications(NotificationListEvent $event)
    {
        if ($this->security->isGranted('IS_ANONYMOUS')) {
            return;
        }

        $notification = new NotificationModel();
        $notification
            ->setId(1)
            ->setMessage('A demo message')
            ->setType(Constants::TYPE_SUCCESS)
            ->setIcon('far fa-envelope')
        ;
        $event->addNotification($notification);

        $event->addNotification(new NotificationModel('Another message', Constants::TYPE_ERROR));
        $event->addNotification(new NotificationModel('Message 3', Constants::TYPE_INFO));
        $event->addNotification(new NotificationModel('Message 4', Constants::TYPE_WARNING));
        $event->addNotification(new NotificationModel('Message 5', Constants::TYPE_INFO, 'far fa-flag'));
        $event->addNotification(new NotificationModel('Message 6', Constants::TYPE_SUCCESS));

        if (!$this->security->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            return;
        }

        $notification = new NotificationModel('You are logged-in!', Constants::TYPE_SUCCESS, 'fas fa-sign-in-alt');
        $notification->setId(2);
        $event->addNotification($notification);
    }
}`

With this code, the counter/badge are on 0 but I have always the icon and the badge

**Comment by kevinpapst** [comment]
Overwrite the blocks and add a check like`{% if app.user %}`:
https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/views/layout/default-layout.html.twig#L52

**Comment by Grazulex** [comment]
Great..simple :-)
