### ISSUE TITLE
Are there any plans to replace FOSUserBundle with another?

### ISSUE THREAD

**Issue by nickicool** [kevinpapst/AdminLTEBundle#157]
I am not an experienced programmer, but it seems to me that symfony 5.1.10 is the latest version with which it is possible to use FOSUserBundle (with crutches). 

1. Are there any plans to replace this bundle with another one? 
2. Is it possible to disable FOSUserBundle in your bundle to remove it while continuing to use kevin papst/adminlte-bundle? Without this, it is no longer possible to use Doctrine 3 and Twig 3 (I may be wrong).

**Comment by kevinpapst** [comment]
FosUserBundle is not required at all:
https://github.com/kevinpapst/AdminLTEBundle/blob/master/composer.json#L20

It is just (still) widely used and this bundles has some built-in options to make the adoption easier.
You don't need FOSUB and can use anything you want for user management

**Comment by kevinpapst** [comment]
I am using this bundle in my app without FOSUserBundle and I am trying to reduce the internal coupling.
See #163 for example.
If you want to help: raise PRs and if you have problems: please give me details
