### ISSUE TITLE
DateTime, Date and birthday type format not work

### ISSUE THREAD

**Issue by joanv38** [kevinpapst/AdminLTEBundle#158]
Hi there,

Maybe it has something wrong but I don't see a way to update the format of every dateType when you build a form.
The format you should use as parameter (  'format' => 'yyyy-MM-dd' for example) don't work  and i didn't found some documentation who explain this part, so my question is there a way to switch the format or we need to overide all the date widget part?

Thanks.

Kind regards.

**Comment by kevinpapst** [comment]
Include proper examples, best is to base them on the demo app. Otherwise I cannot help.
