### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by pacid** [kevinpapst/AdminLTEBundle#164]
Sorry to be a pain, but what does it actually do? I see all the technical stuff, which symfony version used, but if you were to make a short documentation of actual features that would be great.

- What do you use it for?
- What is the reason why I should use it?
- What are the examples of usage (your typical use?)
- What are the pre-requisites for me to use this bundles (do I need to create entities myself or is there a builder? If I need to build it myself, is there a required format/data structure I need to stick to? Examples?)

Thanks, I hope I'm not the only one and this will help spread the awarness of this potentially great piece of software!

**Comment by pacid** [comment]
```
Two main layouts for main application and security (login, forgot password, register account...)
Support for Symfony 4.x
Support for KNPMenuBundle
Support for FOSUserBundle
Webpack-Encore support for building assets
Event-driven handling of menu entries, tasks and notifications
Translations for: english, german, italian, czech, spanish, russian, arabic, finnish, japanese, swedish, portuguese (brazilian), dutch, french, turkish, danish, chinese, slovakian, basque, polish, esperanto, hebrew, romanian (please help translating it to more languages)
Based on AdminLTE 2.4.8
Using FontAwesome 5
```
What does this mean "Two main layouts for main application and security (login, forgot password, register account...)
". Theme as in already build-in functionality? Or if I build the register/login part you're providing a theme? Other than that these are dependencies, not features. So not sure what it does really.

**Comment by kevinpapst** [comment]
As this is open source, you can provide this documentation as well as PR. Besides that, thanks for your feedback.
