### ISSUE TITLE
Suggestion for FOSUserBundle Layout

### ISSUE THREAD

**Issue by juizmill** [kevinpapst/AdminLTEBundle#20]
I'm finding the layout very strange https://github.com/kevinpapst/AdminLTEBundle-Demo/blob/master/templates/bundles/FOSUserBundle/layout.html.twig on line 3 we have the block **logo_login**  but in the other templates we also have it https://github.com/kevinpapst/AdminLTEBundle-Demo/blob/master/templates/bundles/FOSUserBundle/Registration/register.html.twig

I noticed that the layout https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/views/FOSUserBundle/layout.html.twig is not being used. 

I think it would be interesting to use the layout https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/views/FOSUserBundle/layout.html.twig in the other FOSUserBundle view to avoid duplicate lines. 

I think it could be used in line 1 of the other files for example https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/views/FOSUserBundle/Security/login.html.twig

**Comment by kevinpapst** [comment]
I know its weird, but that is related to the way the FOSUserBundle uses its templates.

All templates that are not overwritten will use the layout file: https://github.com/FriendsOfSymfony/FOSUserBundle/tree/master/Resources/views

The other files (the ones overwritten by AdminLTE) are used in the login screen.
So its two different use-cases:
- anonymous user
- logged in users

These two use-cases / user-groups cannot share the same layout.

I already worked on that, as I find duplicating code annoying as well ;-) but I couldn't find a solution that properly worked for all use-cases. But if you find one, I will accept any Pull request!

**Comment by kevinpapst** [comment]
No further feedback, closing.
