### ISSUE TITLE
KNP_MENU options are not used

### ISSUE THREAD

**Issue by laurentHCM** [kevinpapst/AdminLTEBundle#21]
Hi,

I think that the options knp_menu in configurations file are never used.
In order to use the knp_menu I had to change the default values in the function configureDefaults in **ContextHelper.php**
Can you confirm if my reading is correct ?
In that case I can try to propose a fix if you want.
Thanks for your bundle.

Laurent.

**Comment by kevinpapst** [comment]
Hi @laurentHCM ,
I checked the code and you seem to be right. Thanks for posting!

Currently the ContextHelper receives only the `admin_lte.options` in _construct() and therefor has no access to the keys at `admin_lte.knp_menu`. That is definitely a bug.

The complete configuration is a bit weird right now, I will work on it and post a PR that you can test then. But you can sent in any idea and I will see if that can be incorporated as well.

**Comment by kevinpapst** [comment]
Hey @laurentHCM - 
if you have the time, it would be great if you could test the new branch/PR #22 to see if it now works as expected. I removed the legacy default options from the ContextHelper, they come from the app configuration now.

It works with the demo app, but unfortunately I don't have a test app for the KNPMenu integration yet, so I could use your help.

**Comment by laurentHCM** [comment]
Hi Kevin, thanks a lot for your swift action. I will be back in my home by tonight, I will revert at least on Monday morning.
Enjoy your Sunday and take rest.


Laurent BARBEAU



De : Kevin Papst
Envoyé : dimanche 26 août à 13:11
Objet : Re: [kevinpapst/AdminLTEBundle] KNP_MENU options are not used (#21)
À : kevinpapst/AdminLTEBundle
Cc : laurentHCM, Mention


Hey @laurentHCM<https://github.com/laurentHCM> -
if you have the time, it would be great if you could test the new branch/PR #22<https://github.com/kevinpapst/AdminLTEBundle/pull/22> to see if it now works as expected. I removed the legacy default options from the ContextHelper, they come from the app configuration now.
It works with the demo app, but unfortunately I don't have a test app for the KNPMenu integration yet, so I could use your help.

**Comment by laurentHCM** [comment]
Hi Kevin,

I am sorry  I am so stupid.
I try for several hours to get your fix but I can find the way , either by using composer or only git.
I need to work a bit more or these 2 tools before revert.
Have a nice day.

Laurent.

De : Kevin Papst [mailto:notifications@github.com]
Envoyé : dimanche 26 août 2018 13:11
À : kevinpapst/AdminLTEBundle
Cc : laurentHCM; Mention
Objet : Re: [kevinpapst/AdminLTEBundle] KNP_MENU options are not used (#21)


Hey @laurentHCM<https://github.com/laurentHCM> -
if you have the time, it would be great if you could test the new branch/PR #22<https://github.com/kevinpapst/AdminLTEBundle/pull/22> to see if it now works as expected. I removed the legacy default options from the ContextHelper, they come from the app configuration now.

It works with the demo app, but unfortunately I don't have a test app for the KNPMenu integration yet, so I could use your help.

**Comment by laurentHCM** [comment]
Hi Kevin,

Sorry for the delay, I needed some times to find how to use the PR.
Finally I achieved it but probably not in the good way.
I couldn't find how to do it with composer, so I used only git to get the branch, and then I copied manually the folder in the vendor subdirectory.

I checked the fix and everything is perfect.
Thanks a lot.

Laurent

De : Laurent BARBEAU [mailto:laurent.barbeau156@live.fr]
Envoyé : dimanche 26 août 2018 15:53
À : kevinpapst/AdminLTEBundle
Objet : Re: [kevinpapst/AdminLTEBundle] KNP_MENU options are not used (#21)

Hi Kevin, thanks a lot for your swift action. I will be back in my home by tonight, I will revert at least on Monday morning.
Enjoy your Sunday and take rest.

Laurent BARBEAU


De : Kevin Papst
Envoyé : dimanche 26 août à 13:11
Objet : Re: [kevinpapst/AdminLTEBundle] KNP_MENU options are not used (#21)
À : kevinpapst/AdminLTEBundle
Cc : laurentHCM, Mention

Hey @laurentHCM<https://github.com/laurentHCM> -
if you have the time, it would be great if you could test the new branch/PR #22<https://github.com/kevinpapst/AdminLTEBundle/pull/22> to see if it now works as expected. I removed the legacy default options from the ContextHelper, they come from the app configuration now.
It works with the demo app, but unfortunately I don't have a test app for the KNPMenu integration yet, so I could use your help.
-

**Comment by kevinpapst** [comment]
Hi Laurent,
to use composer, you can edit your projects composer.json and replace the version in the line with kevinpapst/adminlte-bundle

For example this line:
https://github.com/kevinpapst/AdminLTEBundle-Demo/blob/master/composer.json#L12
```
        "kevinpapst/adminlte-bundle": "^2.0",
```
will be replaced with
```
        "kevinpapst/adminlte-bundle": "dev-configuration",
```
afterwards run `composer update kevinpapst/adminlte-bundle`, then you have the branch in your project.

**Comment by laurentHCM** [comment]
Hi Kevin,

Yes thanks a lot.
I was too focused on PR#22 , and just at the end I understood that the branch name was configuration so in composer dev-configuration makes sense.
Next time I will be more trained.
Thanks for your help.


De : Kevin Papst [mailto:notifications@github.com]
Envoyé : lundi 27 août 2018 13:50
À : kevinpapst/AdminLTEBundle
Cc : laurentHCM; Mention
Objet : Re: [kevinpapst/AdminLTEBundle] KNP_MENU options are not used (#21)


Hi Laurent,
to use composer, you can edit your projects composer.json and replace the version in the line with kevinpapst/adminlte-bundle

For example this line:
https://github.com/kevinpapst/AdminLTEBundle-Demo/blob/master/composer.json#L12

        "kevinpapst/adminlte-bundle": "^2.0",

will be replaced with

        "kevinpapst/adminlte-bundle": "dev-configuration",

afterwards run composer update kevinpapst/adminlte-bundle, then you have the branch in your project.

**Comment by kevinpapst** [comment]
Thanks for your feedback!
I will merge the changes tonight and create a new release

**Comment by laurentHCM** [comment]
Thank you.

De : Kevin Papst [mailto:notifications@github.com]
Envoyé : lundi 27 août 2018 14:02
À : kevinpapst/AdminLTEBundle
Cc : laurentHCM; Mention
Objet : Re: [kevinpapst/AdminLTEBundle] KNP_MENU options are not used (#21)


Thanks for your feedback!
I will merge the changes tonight and create a new release
