### ISSUE TITLE
In `user.identifier` stored value `user.username`. This bug?

### ISSUE THREAD

**Issue by nickicool** [kevinpapst/AdminLTEBundle#28]
In our template `vendor\kevinpapst\adminlte-bundle\Resources\views\Navbar\user.html.twig (line 35)` for route generation used `id` parameter:

    <a href="{{ path('adminlte_profile'|route_alias, { 'id' : user.identifier}) }}" class="btn btn-default btn-flat">{{ 'Profile'|trans({}, 'AdminLTEBundle') }}</a>

But in `user.identifier` somehow stored value `user.username` instead `user.id`. This bug or not? How fix that?

I need URL like `http://domain/profile/?id=5`, but now it generate URL like `http://domain/profile/?id=admin`. Because of the mismatch in parameter names I can't use my own route name in the parameter `admin_the_profile: for_user_profile_show`, because in my route `ID` is the number.

    /**
     * Display User entity data.
     *
     * @Route("/user/{id}",
     *     requirements={"id": "\d+"},
     *     methods={"GET"},
     *     name="admin_user_show")
     */
    public function show(User $user): Response
    {
        return $this->render('admin/user/show.html.twig', [
            'user' => $user
        ]);
    }

**Comment by kevinpapst** [comment]
Not really a bug, I assume that most people want to re-use their own implementation of the User entity. 
So the default implementation is just an example. Multiple ways you can go:
- Implement the `UserInterface` on your own Entity, then you can re-use it from the token/security storage: https://github.com/kevinpapst/AdminLTEBundle/blob/master/Model/UserInterface.php
- If you want to use the bundles own implementation, you can overwrite the `UserModel` in your project and implement the `getIdentifier()` method differently
- You sent in a PR with a changed UserModel that allows to set the id differently

**Comment by kevinpapst** [comment]
I quickly added a branch that is backward compatible and has a setId() method on all models. 
Please see the PR #29 
That should fix your problem!

**Comment by kevinpapst** [comment]
Please update via composer to the latest master, then you can use `->setId(x)` on your model and everything should be fine.

**Comment by nickicool** [comment]
Hi Kevin! Thank you for answer and very important job - admin section used in most sites!)) I try do to you tell me:
- install dev version bundle, set in composer.json `"kevinpapst/adminlte-bundle": "@dev"`
- update installs

... installing dev version done! But, now:

- if I used default route `adminlte_profile: fos_user_profile_show` it is nothing changes - profile link still generated as `http://domain/profile/?id=admin`.
- if I used my own route (as I wanted) `adminlte_profile: admin_user_show` - I get error `An exception has been thrown during the rendering of a template ("Parameter "id" for route "admin_user_show" must match "\d+" ("admin" given) to generate a corresponding URL.").` Controller method for route `admin_user_show` I posted early in first message.

I think need do somethink in model, because you say "then you can use ->setId(x) on your model and everything should be fine.". But, how I must change my model - I am not understand. Sorry, I just learning Symfony :). 

Can you help me?

**Comment by nickicool** [comment]
I find solution!!!! :)) I just add `->setId($currentUser->getId())` in `src/EventSubscriber/AdminNavbarUserSubscriber.php`:

        $user = new UserModel();
        $user->setName($currentUser->getUsername())
            ->setId($currentUser->getId())
            ->setUsername($currentUser->getUsername())
            ->setIsOnline(true)

All work fine!
Thank you!

**Comment by kevinpapst** [comment]
Thanks for your feedback :-) I am glad it works!

I know you found it, but for everyone else who reads this ... here is the link for the documentation where it is described how to setup the user-model:
https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/navbar_user.md
