### ISSUE TITLE
Sidebar menu using KNP Menu is missing class

### ISSUE THREAD

**Issue by Holicz** [kevinpapst/AdminLTEBundle#35]
Hi,

when generating sidebar menu using knp menu bundle I get this code:

```html
<section class="sidebar" style="height: auto;">
    <ul>
        <li class="first last">
            <a href="/">
                <i class="fa fa-flag"></i>            
                <span>Home</span>
            </a>            
        </li>
    </ul>
</section>
```

Which is wrong, because `<ul>` tag is missing classes from AdminLTE and the menu does not look as it should. I believe it should have class `sidebar-menu` and to deal with collapsible tree menu it should also have class `tree ` and data attribute `data-widget="tree"`.

**Comment by kevinpapst** [comment]
Hi @Holicz - thanks for taking the time to contribute!

I don't use the KNP Menu bundle actively and after upgrading to the latest AdminLTE version I might have missed these templates.

Are you saying your PR doesn't fix the complete problem and you need some help?

**Comment by Holicz** [comment]
Yes, as you say - it fixes only half of the problem (menu not getting classes). Then there is a problem menus with more levels. If a `<li>` element has submenu inside it needs to have class `treeview` and the submenu (`<ul>`) inside this `<li>` needs class `treeview-menu`.

To show what I mean. Now a two level menu is generated like this:

```html
<li class="last">
    <a>
        <span>Level 1</span>
        <span class="pull-right-container">
            <i class="fas fa-angle-left pull-right"></i>
        </span>
    </a>

    <ul class="sidebar-menu tree" data-widget="tree">
        <li class="first last">
            <a>
                <span>Level 2</span>
            </a>
        </li>
    </ul>
</li>
```

And it needs to be generated like this:
```html
<li class="last **treeview**">
    <a>
        <span>Level 1</span>
        <span class="pull-right-container">
            <i class="fas fa-angle-left pull-right"></i>
        </span>
    </a>

    <ul class="sidebar-menu tree **treeview-menu**" data-widget="tree">
        <li class="first last">
            <a>
                <span>Level 2</span>
            </a>
        </li>
    </ul>
</li>
```

Unfortunatelly, I am not able to implement this behavior.

**Comment by Holicz** [comment]
@kevinpapst, I just tested the branch and it works like a charm, thank you very much for that bundle and work on the KNP menu!

Also, my PR can be declined now as you covered these things in your branch.
