### ISSUE TITLE
Incorrect checking if variable is defined in Twig

### ISSUE THREAD

**Issue by Holicz** [kevinpapst/AdminLTEBundle#38]
In Twig it should be checked if variable is present by `{% if variable is defined %}` not by the shorter syntax `{% if variable %}` as it will throw exception `Variable "variabe" does not exist.` [DEMO](https://twigfiddle.com/fw0uxu)

However, there are some places in this bundle, where to wrong syntax is used.

I will provide PR in a while.

**Comment by Holicz** [comment]
I am sorry for misunderstanding the problem. The only place I found the problem was in security layout with `{% if csrf_token %}`. But `csrf_token` should be always set (I had a bug in my code passing the variable to the layout).

**Comment by kevinpapst** [comment]
[Its a function](https://symfony.com/doc/current/reference/twig_reference.html#csrf-token) and can be missing. 
Can't remember if it is already missing after deactivation in
```
framework:
             csrf_protection: { enabled: true
```
or when the form component is not added as app dependency - and maybe thats not even the case anymore in 4.1. But there was a bug previously, when it was added without the check.
