### ISSUE TITLE
translation of "required field text"

### ISSUE THREAD

**Issue by behalp** [kevinpapst/AdminLTEBundle#42]
I have found small translation bug in version 2.1.3

In file Resources\views\layout\form-theme.html.twig there is in current version on line 166:

`<sup class="required" title="{{ "This is a mandatory field"|trans({}, translation_domain) }}">`

but it should be:

`<sup class="required" title="{{ "This is a mandatory field"|trans({}, 'AdminLTEBundle') }}">`

after this fix text "This is a mandatory field" is correctly translated based on bundles translation files.

**Comment by kevinpapst** [comment]
Thanks, will be fixed in the next version
