### ISSUE TITLE
Horizontal form

### ISSUE THREAD

**Issue by darthf1** [kevinpapst/AdminLTEBundle#46]
Is it possible to add a form theme for a horizontal form? Or what would be the best way to do it myself? 

I noticed your form theme extends ''bootstrap_3_layout.html.twig'' and not 'bootstrap_3_horizontal_layout.html.twig', but changing only that messes up a lot of things.

**Comment by kevinpapst** [comment]
Do you mean something like this (upper right):
https://adminlte.io/themes/AdminLTE/pages/forms/general.html

Great idea, unfortunately I don't have the time right now. But if you could help with investigating, I am totally willing to support you and also ship this theme with two different form layouts.

**Comment by darthf1** [comment]
Yes exactly that. Ok, i'll have a look at it. Thanks.

**Comment by kevinpapst** [comment]
Please check the attached PR and let me know if that works for you:
https://github.com/kevinpapst/AdminLTEBundle/pull/47

The demo application has a branch as well, showcasing the new form theme:
https://github.com/kevinpapst/AdminLTEBundle-Demo/pull/5

**Comment by kevinpapst** [comment]
Feedback is welcome!

**Comment by kevinpapst** [comment]
If anyone reads this and could help me with testing the pull request I'd be happy to get your feedback!
