### ISSUE TITLE
SF 3.4 compatibilty ? 

### ISSUE THREAD

**Issue by numerogeek** [kevinpapst/AdminLTEBundle#48]
Hello, 

Is there a tagged version of your repo compatible with SF 3.4 ? 
Because the very last one seems to be compatible only with 4 ?

thank you

**Comment by kevinpapst** [comment]
Nope, sorry, it was written for SF 4 exclusively.
But you could try to fork it and change the composer version constraints. There is a good chance that it works (probably with a handful of necessary adjustments).
