### ISSUE TITLE
Extend webpack encore usage

### ISSUE THREAD

**Issue by lucasaba** [kevinpapst/AdminLTEBundle#5]
I'm trying to extend the webpack configuration used for adminlte. In this way I could use the createSharedEntry to minimize the js size and create new javascript app that uses the jquery/bootstrap etc from admin-lte.js (I'm just beginning to use webpack-encore so...I hope I'm not sying anything stupid...).

To do so:

- I've copied vendor/kevinpapst/adminlte-bundle/webpack.config.js and vendor/kevinpapst/adminlte-bundle/package.json to my root folder
- Installed all dependencies (yarn add @symfony/webpack-encore --dev)
- I've updated webpack.config.js

The main changes are as follow:
```javascript
    .setOutputPath('./vendor/kevinpapst/adminlte-bundle/Resources/public/')
    .setPublicPath('/bundles/adminlte/')
    .setManifestKeyPrefix('bundles/adminlte/')
    .addEntry('adminlte', './vendor/kevinpapst/adminlte-bundle/Resources/assets/admin-lte.js')
```
When i try to build everything (./node_modules/.bin/encore dev) I get this error:
```bash
These dependencies were not found:

* admin-lte/dist/js/app.js in ./vendor/kevinpapst/adminlte-bundle/Resources/assets/admin-lte.js
* admin-lte/plugins/chartjs/Chart.min.js in ./vendor/kevinpapst/adminlte-bundle/Resources/assets/admin-lte.js
```

I think app.js could be deleted without any problem and that chartjs could be installed via yarn in node_modules.... Am I right ? Am I following the correct steps ?

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 4.1.1  |
| AdminLTEBundle  | 1.1.1  |
| Operating System  | Ubuntu 18.4  |
| Yarn  | 1.6.0  |
| Node | 8.10.0|

**Comment by lucasaba** [comment]
And, by the way, I had some problem with Resources/assets/admin-lte.scss. I had to update the fontawsome imports in the following way:

```scss
@import '~@fortawesome/fontawesome-free/scss/fontawesome';
@import '~@fortawesome/fontawesome-free/scss/regular';
@import '~@fortawesome/fontawesome-free/scss/solid';
@import '~@fortawesome/fontawesome-free/scss/brands';
```

**Comment by kevinpapst** [comment]
I am in no way an expert in that frontend-stack building as well... but I am trying to help as good as I can. First of all, here are two js examples of how I use the bundle:

This one simply uses the original files to create its own app.js and app.css
- https://github.com/kevinpapst/AdminLTEBundle-Demo/blob/master/assets/adminlte-demo.js
- https://github.com/kevinpapst/AdminLTEBundle-Demo/blob/master/webpack.config.js

This one adds stuff on top:
- https://github.com/kevinpapst/kimai2/blob/master/assets/js/app.js
- https://github.com/kevinpapst/kimai2/blob/master/webpack.config.js

Both versions do not try to remove stuff from the app, so the use-case is different.

Just for reference, here is an example from the project history where I didn't have that bundle. Probably you can grab some inspiration about how to set the path correct:
https://github.com/kevinpapst/kimai2/blob/b299302da4ae6b88ecaf187ceb020799f466ff64/assets/js/app.js

I installed all dependencies I could find via npm/yarn, charts.js wasn't one of them. 
There is a chartsjs available, but it seems to be another "chartjs" and not the one which is used in AdminLTE. But you only need if, if you want to draw these exact charts. So if you find it in npm, please let me know, I'd like to replace it as well - just couldn't find it.

If you remove the app.js, some layout functionality won't work correctly, I wouldn't recommend it.

Regarding FontAwesome: did you use the bundles packages.json as starting point?
https://github.com/kevinpapst/AdminLTEBundle/blob/master/package.json
Which FontAwesome version are you using?

**Comment by kevinpapst** [comment]
Using AdminLTE 2.4.8 is definitely "wrong" - well, I mean: not supported. 
There were some changes made which were incompatible with the HTML / CSS which used in this bundle, as far as I remember.
But the dependency "chart.js" in interesting, will check it out.

I will try with FontAwesome 5.1.1 , can't believe that they changed the structure in a patch release, that wouldn't be semver compatible.

Can you try to downgrade your packages, just to see if it works?

If you find something (probably I am probably using the version pinning wrong in packages.json) let me know. I would be glad to make the bundle more fail-safe.

**Comment by kevinpapst** [comment]
Yep, I am currently reading their semver instructions: https://docs.npmjs.com/misc/semver and will update the packages.json. I will invite you to the PR for testing if thats okay.

Regarding FontAwesome: https://github.com/FortAwesome/Font-Awesome/releases/tag/5.1.1
> Removed "fa-" prefix from Less and Sass style bundles filenames 
They really changed the filenames in a patch release... not much to say here ^^ besides: I will fix that as well.

**Comment by kevinpapst** [comment]
PRs would be awesome! The more documentation the better.
I will merge the PR and release a new version then.
