### ISSUE TITLE
Plans for AdminLTE 3 ?

### ISSUE THREAD

**Issue by rufinus** [kevinpapst/AdminLTEBundle#51]
Are you planning to branch for AdminLTE 3 (Bootstrap 4)?

https://github.com/almasaeed2010/AdminLTE/tree/v3.0.0-alpha
https://adminlte.io/themes/dev/AdminLTE/index3.html

**Comment by kevinpapst** [comment]
Yes I do have and I would like to. 
But unfortunately development seems to have stopped a year ago and I am unsure how to proceed as its only an alpha version right now.

**Comment by rufinus** [comment]
it seems on the v3-dev branch is a little bit more active - but also not really up to speed.
https://github.com/almasaeed2010/AdminLTE/commits/v3-dev

**Comment by PouleR** [comment]
It seems AdminLTE 3.0.0-beta.2 is available (released 5 days ago), it looks like a v3 will be available in the near future. https://github.com/ColorlibHQ/AdminLTE/issues/2190

**Comment by kevinpapst** [comment]
I have seen that, but there are still a lot of open points in the linked list.
Not sure if it is a good idea to start with it right away...
Maybe I find the time for a test branch, but I don't promise anything. 
If anyone wants to help with that, please open a PR!

**Comment by yudhir** [comment]
It is now RC version .

**Comment by kevinpapst** [comment]
Yes, I know. I am following them as well. 
If anyone wants to contribute, I'd be happy to work together on a shared branch.

**Comment by yudhir** [comment]
Basically new to symfony and Web . If you create a branch i may read up .

**Comment by TonySma** [comment]
Currently working with version 2, but Bootstrap and AdminLte V3 have so much new things. 
Ready to help @kevinpapst

**Comment by Ousret** [comment]
It is now a final release.

**Comment by kevinpapst** [comment]
Oh and they released an upgrade guide, wow: https://adminlte.io/docs/3.0/upgrade-guide.html

Who wants to start?

**Comment by Gonzalo1987** [comment]
Criquet… criquet… 

I doesn't mind help if I can, but I believe that you know better than anyone how start.

I imagine that you haven't enough time for the new release @kevinpapst

**Comment by kevinpapst** [comment]
Indeed, time is the limiting factor.

The main adjustments is (hopefully) the frontend build process.
It should be upgraded to the new Symfony standards when on it, but thats just minor stuff. 
Then checking HTML changes.

If someone wants to start: please go ahead! I am totally willing to help. 
But I don't have the need myself right now, so for me there is no pressure.

**Comment by rufinus** [comment]
@kevinpapst FYI i start on integrating AdminLTE3 in https://github.com/cwd/AdminLTEBundle/tree/adminlte3

I use your Demo app as basis.

**Comment by yudhir** [comment]
Any Updates on Admin LTE 3

**Comment by yudhir** [comment]
FOSUserbundle is  not recommended and in the future it should be removed .

**Comment by kevinpapst** [comment]
If you want to speed up things, you could all help testing this PR:
https://github.com/kevinpapst/AdminLTEBundle/pull/107
Integration of AdminLTE v3 is in very good progress.

**Comment by tacman** [comment]
Just jumping in now, and would like to help, especially with the Symfony part.   I'd like to propose that we drop support for FOSUserBundle and simply follow the Symfony best practices for creating a security system.  Symfony 5.1 will even support creating the code for resetting the user password (https://symfony.com/blog/new-in-makerbundle-1-15-make-reset-password-and-make-message).

I may be able to help out with updating the demo bundle and this bundle to support Symfony 4.4 and Symfony 5, but the Symfony 5 support would completely drop FOSUserBundle.  The way I've done this with other projects is to move the security to the _application_ (it's really fast and easy to do that now), then pass the necessary routes (app_homepage, app_login, etc.) to the Admin Bundle.  The admin bundle also render KnpMenu's, so that the valid routes happen in the Menu Builder rather than Twig.

What do people think of dropping FOSUserBundle?

**Comment by kevinpapst** [comment]
The FOSUserBundle integration is totally optional, so I don't see why it should be dropped. Yes, I am not a fan of it either, but it is still used in so many apps, so why not keep it?

But I would totally agree if we turn the argument around: lets make it easier to support Symfony best practices and advocate to use them (while still having the FOSUserBundle support as is).
I would appreciate every help with that topic!

Do you think the topic is connected to the redesign in AdminLTE v3?

**Comment by tacman** [comment]
Somehow I thought FOSUserBundle was required, but I must have been confusing the demo app with the bundle.  

I attempted to upgrade the demo app to Symfony 5, but ran into a few issues, so instead started a new demo app that uses Symfony 5 and doesn't use FOSUserBundle.  I'll post a link to that later.

**Comment by cavasinf** [comment]
Hey @kevinpapst, any news for that topic ?
Looking for integrating a more recent version of BootStrap and FontAwesome, but upgrading AdminLte himself should do the trick !

**Comment by evskorobogatij** [comment]
Hi.
I what try to use branch adminlte-v3
`
composer require kevinpapst/adminlte-bundle ^4.0
`
But I get error
`
 [InvalidArgumentException]
  Could not find package kevinpapst/adminlte-bundle in a version matching ^4.0
`

**Comment by kevinpapst** [comment]
```
composer require kevinpapst/adminlte-bundle dev-adminlte-v3
```

**Comment by ejolivares** [comment]
> Somehow I thought FOSUserBundle was required, but I must have been confusing the demo app with the bundle.
> 
> I attempted to upgrade the demo app to Symfony 5, but ran into a few issues, so instead started a new demo app that uses Symfony 5 and doesn't use FOSUserBundle. I'll post a link to that later.

Hey @tacman, did you ever have a chance to complete the demo that uses Symfony 5 instead of FOSUserBundle? Thank you

**Comment by tacman** [comment]
Yes, I think so, try this:

    git clone git@github.com:tacman/AdminLTEBundle-Demo.git
    git checkout symfony5
    composer install && yarn install && yarn run encore dev   
    symfony server:start

**Comment by tacman** [comment]
I'm having an issue with using the js and css within encore on my branch.  The demo works, but it'd be better if it worked with encore.

**Comment by ejolivares** [comment]
> I'm having an issue with using the js and css within encore on my branch. The demo works, but it'd be better if it worked with encore.

Thank you again for doing this. I mostly have it up and running. Did you create a user/password for the demo?

**Comment by tacman** [comment]
I don't think so.  I'm working on another bundle (SurvosBaseBundle) that
adds things like creating users (with roles and password) and incorporating
encore.  But I use colorlib's package to get the js and css, and your
bundle for everything else.  Of course, that duplicates the code.

If you have some time, I'll put together a demo for that.

**Comment by kevinpapst** [comment]
Can you please open a new issue to discuss that topic, it seems rather off-topic for the AdminLTE v3 migration.

**Comment by kevinpapst** [comment]
Anyone using the AdminLTE v3 branch here? Please head over to #161
