### ISSUE TITLE
Symfony 3.4 Demo Link

### ISSUE THREAD

**Issue by ahmetozalp** [kevinpapst/AdminLTEBundle#54]
I want an example for 3.4, can you please share

**Comment by kevinpapst** [comment]
> AdminLTE bundle for Symfony 4 - an backend/admin theme for easy integration with SF4. Its based on the AdminLTE Template and built with webpack-encore. Supports KNPMenuBundle and FOSUserBundle.

Don't know and don't care about SF 3.4.
Use the original bundle instead: https://github.com/avanzu/AdminThemeBundle

**Comment by kevinpapst** [comment]
But to be fair: I think it should work with 3.4 as well.
Just use the normal demo application, there is no big difference to 3.4:
https://github.com/kevinpapst/AdminLTEBundle-Demo
