### ISSUE TITLE
Variable "items" does not exist in knp-breadcrumb.html.twig 

### ISSUE THREAD

**Issue by matrixino** [kevinpapst/AdminLTEBundle#56]
I'm new to Symfony/Twig so take it with a grain of salt. In knp-breadcrumb.html.twig the {% endfilter %} tag should go after {% endfor %} otherwise the items variable is lost and result in "Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "items" does not exist." Actually IDK why a twig filter should invalidate a variable, but that happens to me.

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 4.2  |
| AdminLTEBundle  | 2.4.1  |
| Operating System  | GNU/Linux  |

**Comment by kevinpapst** [comment]
You are referring to [this line](https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/views/Breadcrumb/knp-breadcrumb.html.twig#L8), right? 
Haven't tried it yet but sounds interesting. Which twig version are you using? 
I [recently changed](https://github.com/kevinpapst/AdminLTEBundle/pull/55) from `{% spaceless %}` to `{% filter spaceless %}` and I believe that it was working before... 
I don't have the time right now to check the compiled template whether this is a twig bug or not and I couldn't find something in the twig documentation.
Your solution was to move the line? Could you try to remove the complete filter and/or use the whitespace delimiter `{%- -%}` to see if that works better?

**Comment by matrixino** [comment]
No, I'm referrign to the {for} at line 10. Before the {% endfilter %} items is still defined, checked with dump().  I'm using "symfony/twig-bundle": "4.2.*"
Yes, my solution was to move the line {% endfilter %} just after the {% endfor %}. Also, it's working with {% spaceless %} {% endspaceless %}.
I searched the docs too but couldn't find any reference to this behaviour, apparently variables declared inside filter block are lost outside (I actually don't know if this is true with other blocks aswell, since I'm new to Twig).

**Comment by kevinpapst** [comment]
Yeah, I meant "the variable in linked line" is missing afterwards.
Just tested and can confirm it and I think this is by design (see the linked issue at Twig itself).
Do you want to submit a PR for the fix?

**Comment by matrixino** [comment]
PR submitted. I didn't change the other 2 files involved in the <% spaceless %> change because I think they should be ok already. form-theme-horizontal.html.twig doesn't declare any var inside and form-theme.html.twig already closes the filter tag at the end. I didn't check if variables declared _before_ the <% filter %> are available inside (ie. the error var in those temapltes), but I don't see why they shouldn't.

**Comment by kevinpapst** [comment]
Thanks! I'll merge that, but before creating a bug release I want to see where the discussion in the twig issue is leading to.

**Comment by kevinpapst** [comment]
A need tag was introduced for Twig 1.4 called `apply`: https://github.com/twigphp/Twig/pull/2977
But as Twig 1.4 is not there for a longer time, I say we stick with your solution.

**Comment by fabpot** [comment]
The new tag will be part of Twig 1.40, which will be released in a few days (less than 2 weeks for sure).

**Comment by kevinpapst** [comment]
This is "just" a Symfony theme bundle and for BC reasons I cannot require users to upgrade to Twig 1.4. Thats why I am going to use the filter spaceless for a while.
But thanks for your feedback and the quick solution 👍

**Comment by stof** [comment]
Symfony already requires a recent version of Twig.
