### ISSUE TITLE
Console error after update

### ISSUE THREAD

**Issue by makshv** [kevinpapst/AdminLTEBundle#62]
After bundle update I run command `bin/console cache:clear` and received the following console error:

>  Invalid resource provided: ".../vendor/kevinpapst/adminlte-bundle/Resources/translations/AdminLTEBundle.pt_BR.xliff"; Errors: [ERROR 1824]   
  Element '{urn:oasis:names:tc:xliff:document:1.2}file', attribute 'target-language': 'pt_BR' is not a valid value of the atomic type 'xs:language'.

This happened after PR: 
https://github.com/kevinpapst/AdminLTEBundle/pull/61

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 4.2.7  |
| AdminLTEBundle  | 2.5  |
| Operating System  | Debian  3.16.51-3+deb8u1  |

**Comment by kevinpapst** [comment]
Thanks for the report. I expected the translation to be tested before sending in the PR. 
Sorry, should have verified that myself.
Created 2.5.1 which fixes the issue.
