### ISSUE TITLE
How can I disable the form theme?

### ISSUE THREAD

**Issue by dramentol** [kevinpapst/AdminLTEBundle#71]
Simple question: how can I disable the form theme?

I'm using this bundle for the back office only, so I want to use the symfony form theme for my front office

**Comment by dramentol** [comment]
ok, I've found it

on config/packages/twig.yaml:
```
twig:
    form_themes:
        - 'form_div_layout.html.twig'
```

**Comment by kevinpapst** [comment]
Thanks for your feedback.
And as reference for other users: https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/form_theme.md#overwrite-form-theme-in-your-application
