### ISSUE TITLE
Navbar messages: total number of messages as separate parameter from messages

### ISSUE THREAD

**Issue by lucasaba** [kevinpapst/AdminLTEBundle#73]
FEATURE REQUEST:
I'm trying to integrate [FOSMessageBundle](https://github.com/FriendsOfSymfony/FOSMessageBundle) with admin lte bundle and the navbar messages component. Since I'm using Symfony 4, I'm having no problem with the event subscriber but: what if many users have many unreaded messages ? Actually you need to insert all messages in the event and then display just the first _max_ messages.

Would it be fine to add a method in MessageListEvent to accept the total number of messages and update messages.html.twig accordingly ?

Do you think I could make a PR with this update ?

**Comment by kevinpapst** [comment]
You mean that the `MessageListEvent::setTotal()` function is missing and instead there is a `getMax()` method which is actually never used? And `NotificationListEvent::setTotal()` is available, but for messages it is missing, yes that look wrong.
Go ahead and create a PR. I am not sure what you want to change in the template, but I will see...

**Comment by lucasaba** [comment]
#74 closed the issue
