### ISSUE TITLE
Boxes collapse all boxes

### ISSUE THREAD

**Issue by ARE2KUSU** [kevinpapst/AdminLTEBundle#77]
I have recently updated the bundle.
I have multiples boxes into the parent box. But when i want to collapse only one of these, all of these collapse.
Before the update it worked.
There is my code of one child :
`
                            <div class="box-header with-border">

                                <div class="box-title">
                                    <span class="label label-default">Mail</span>
                                </div>
                                &nbsp;le 14/06/2019 à 08:40 par 

                                <div class="box-tools pull-right">
                                    <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                        <i class="fa fa-minus"></i>
                                    </button>
                                </div>

                            </div>

                            <div class="box-body">

                              <div class="row">
                                    <div class="col-md-12">
                                        <label>Commentaire : </label>
                                        Envois de l'email qui contiens les informations de connexion
                                    </div>
                                </div>

                               </div>
`
SOLUTION : 
https://github.com/ColorlibHQ/AdminLTE/issues/2088#issue-427275538

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 4.3.1  |
| AdminLTEBundle  | 2.8.1  |
| Operating System  | GNU/Linux  |

**Comment by kevinpapst** [comment]
I guess you want to say you are using `{% embed '@AdminLTE/Widgets/box-widget.html.twig' %}` inside the `{% block box_body %}` of another `{% embed '@AdminLTE/Widgets/box-widget.html.twig' %}` ?

This bundle does not handle or change the javascript part of the collapse events. 
Please file a bug in the upstream repo for AdminLTE. 

You can also try to downgrade the original theme by changing your packages.json:
```
        "admin-lte": "~2.4.8",
```
to the last release and rebuild the JS part.

**Comment by SXPREAM** [comment]
I have downgraded to 2.2 it worked now but newer version have same issue.

**Comment by kevinpapst** [comment]
Hm, ocin plochoi. 
You are right, with [this commit](https://github.com/kevinpapst/AdminLTEBundle/pull/47/files) for kevinpapst/adminlte-bundle:2.3 the AdminLTE theme was upgraded as well:
```
admin-lte@~2.4.8:
	  version "2.4.8"
	  resolved "https://registry.yarnpkg.com/admin-lte/-/admin-lte-2.4.8.tgz#35edb2b7857af7fcfed7355c83649d5abd09a501"
	  version "2.4.9"
	  resolved "https://registry.yarnpkg.com/admin-lte/-/admin-lte-2.4.9.tgz#effc04dbb587ccb7d674d4cf663cc141f925ed73"
	  integrity sha512-+u3zt5sWPPT8HmBvRg4F8IGZPaE5wD0K10+IjXoynfe/jEUrMMj+4eA1LGH9fMK6QulmFr1NCtc1Tk+mTgC24A==
```
Are you using the assets from this bundle or do you build them by yourself?
You could easily downgrade to `admin-lte@~2.4.8` and re-compile the assets.
If you don't know how, you can check the Demo-App, everything is in there.

There are a lot of issues regarding the collapse behaviour, eg. https://github.com/ColorlibHQ/AdminLTE/issues/1725

Try to file a bug in their issue tracker.

**Comment by SXPREAM** [comment]
I use bundle assets. I researching how to fix this issue on the AdminLte issue tracker.
Thx.

**Comment by ARE2KUSU** [comment]
I just found the solution here :
https://github.com/ColorlibHQ/AdminLTE/issues/2088#issue-427275538

I fix this issue by changing public/bundles/adminlte/adminlte.js line 44 "expandingEvent" by "c".

This issue is fixed on their repository.
