### ISSUE TITLE
Feature request: THEME_NAVBAR_USER event option to hide/disable membersince

### ISSUE THREAD

**Issue by RickJelier** [kevinpapst/AdminLTEBundle#79]
Hello,
I would like to disable/hide the member since field in the navbar so that this doesn't show (just like setShowProfileLink, but then setShowMemberSince obviously) this wouldn't be too hard I think.

A workaround I could do is hide the field with css, but this just seems ugly.

If the feature get's accepted I might do the work myself and submitting a pr.

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 4.3.* |
| AdminLTEBundle  | 0.9/dev-master/commit/tag  |
| Operating System  | Windows 8.1 pro  |

**Comment by kevinpapst** [comment]
Sure I will accept a PR, as long as the default behaviour isn't changed.

I haven't tried, but can't you simply overwrite the translation with an empty string?
What do you think about checking`{%if not user.memberSince is null %}`? Then we could avoid a new method in the event.

**Comment by RickJelier** [comment]
I haven't tried overwriting the translation. I might try this as a last-resort option.

When checking `{%if not user.memberSince is null %}` then the contructor in the UserModel class must be changed because of line 61 `$this->memberSince = $memberSince ?: new \DateTime();`

**Comment by kevinpapst** [comment]
Good spotting, I didn't check that.
What about putting a twig block around it? Then users could overwrite / extend the template and empty that block.

I am also fine with adding another method, but it kinda feels wrong to me to influence the html from a backend event (the current methods are only there, as they were migrated from the original bundle).

**Comment by RickJelier** [comment]
My custom `base.html.twig` extends the `default-layout.html.twig` as provided by the bundle. On line 62 of `default-layout.html.twig` there is a call to render the controller `AdminLTEBundle:Navbar:user` which executes userAction in the NavbarController, which in turn responds with the render `user.html.twig` template.

But: because the block will be in the template that is rendered by the `render(controller('AdminLTEBundle:Navbar:user'))` function you can't override it. You can however override block navbar_user in `default-layout.html.twig` and replace it with a call to another controller that will render a custom `user.html.twig`

**Comment by kevinpapst** [comment]
No, you are wrong with that assumption.

Lets assume the theme file would have this block:
```
            <p>
                {{ user.name }} - {{ user.title }}
                {% block member_since %}
                    <small>{{ 'Member since %date%'|trans({'%date%': user.memberSince|date('m.Y') }, 'AdminLTEBundle') }}</small>
                {% endblock %}
            </p>
```

Then you could create the file `templates/bundles/AdminLTEBundle/Navbar/user.html.twig` with this content:
```
{% extends "@!AdminLTE/Navbar/user.html.twig" %}
{% block member_since %}
    x
{% endblock %}
```
Then the "Member since foo-bar" would be replaced with an "x".

Attention when overwriting bundle templates, the `!` in the file name is important, [see here](https://symfony.com/doc/current/bundles/override.html#templates) if you want to extend the original one.

What do you think which way is the best to go? My vote goes to adding one or more blocks which can be overwritten by the app.

**Comment by RickJelier** [comment]
Ah, the more you know I guess. Didn't know this was a thing.
My vote then also goes to adding more blocks to the template that can be overwritten, this would be very nice because this makes the bundle more customizable for the user.

**Comment by kevinpapst** [comment]
Yes I would double that opinion.
You know the best which blocks you need right now... so: Do you want to provide a PR for this?

**Comment by RickJelier** [comment]
Yes, will do

**Comment by RickJelier** [comment]
Here you go #81

**Comment by kevinpapst** [comment]
That was a good outcome, thanks for the discussion and PR
