### ISSUE TITLE
refreshBox function is not available

### ISSUE THREAD

**Issue by glerendegui** [kevinpapst/AdminLTEBundle#84]
Trying to call refreshBox function from custom javascript is not working. The function are actually included by adminlte.js but it is renamed by minifier:
adminlte.js line 44
`a=function(t,n){if(this.element=t,this.options=n,t `

AdminLTE doc available in https://adminlte.io/docs/2.4/js-box-refresh
DataAPI is working but jQuery method is not

`$('element').refreshBox({}) ` throws  $(...).refreshBox is not a function

trying on 2.8.5 version

**Comment by glerendegui** [comment]
The function real name is "boxRefresh".
AdminLTE docs seems to be wrong.

**Comment by kevinpapst** [comment]
Thanks for posting the solution! Glad you solved it.
