### ISSUE TITLE
 Add support to new Symfony 4.3 EventDispatcher behavior

### ISSUE THREAD

**Issue by llaville** [kevinpapst/AdminLTEBundle#85]
Please write here a description of your problem. Don't hesitate and add enough
information to fix your problem properly - you can even use images!

If this is a BUG REPORT:

  * Describe what you wanted to do and the wrong result you got.
  * Fill the Debug info table below
  * (Optional) If they are useful, include logs, code samples, screenshots, etc.

If this is a FEATURE REQUEST:

  * Describe the new feature briefly.
  * If you consider or have knowledge submit a Pull Request.

Hello,

Even, if I don't used the latest version available of bundle (2.8.5), master branch code are impacted.
See :
- https://github.com/kevinpapst/AdminLTEBundle/blob/master/Controller/NavbarController.php#L50
- https://github.com/kevinpapst/AdminLTEBundle/blob/master/Controller/NavbarController.php#L77
- https://github.com/kevinpapst/AdminLTEBundle/blob/master/Controller/NavbarController.php#L104
- https://github.com/kevinpapst/AdminLTEBundle/blob/master/Controller/NavbarController.php#L125

See Symfony Official Announcement :  https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching

Fix seems easy by using `Symfony\Component\EventDispatcher\LegacyEventDispatcherProxy`
See https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching#supporting-both-dispatchers 

KR

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 4.3.3  |
| AdminLTEBundle  | 2.8.3  |
| Operating System  | Linux  |

**Comment by kevinpapst** [comment]
PRs are welcome!

**Comment by llaville** [comment]
Even if i'm still in hollidays, i should be able to propose a PR tomorrow

**Comment by kevinpapst** [comment]
Awesome 😀

**Comment by llaville** [comment]
BTW, the most easy solution is to raise Symfony dependency to 4.3 min, for both AdminLTE bundle and demo.

In such case the PR is useless 😉

**Comment by kevinpapst** [comment]
Thats what I was going to propose, but you were faster.
What about bumping the bundle to 3.0 and fixing all open deprecations, including the ones from #80 ?

**Comment by llaville** [comment]
@kevinpapst Any idea about a date for next major release 3.0 (supporting SF 4.3+) ?

**Comment by kevinpapst** [comment]
Can you test PR #89 ?

**Comment by llaville** [comment]
Will do it tomorrow !
