### ISSUE TITLE
Installing in subdomain

### ISSUE THREAD

**Issue by Gonzalo1987** [kevinpapst/AdminLTEBundle#90]
Please write here a description of your problem. Don't hesitate and add enough
information to fix your problem properly - you can even use images!

If this is a BUG REPORT:

I've followed the steps for extending the webpack, but the font-awesome are not in the route of the publicpath of my webpack.config. I don't know what I need to do for install AdminLTE in a subdomain, I can override the plugin with my own CSS, but the browser still try to download the AdminLTEBundle ttfs and woffs.

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 4.3.*  |
| AdminLTEBundle  | 0.9/dev-master/commit/tag  |
| Operating System  | Windows |

**Comment by kevinpapst** [comment]
You need to change the path in 
https://github.com/kevinpapst/AdminLTEBundle/blob/master/webpack.config.js#L8
and recompile the assets

**Comment by Gonzalo1987** [comment]
how can I recompile the assets?

I have modified: /vendor/kevinpapst/adminlte-bundle/webpack.config.js changing: 
.setPublicPath('/sub-path/bundles/adminlte/')

and I have done: php bin/console assets:install and yarn encore dev, but it still trying to get the resources from the root.

**Comment by kevinpapst** [comment]
https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/frontend_assets.md

**Comment by Gonzalo1987** [comment]
I have done 
`npm run build`
too but nothing changes, the routes still being root relatives and the 404 message still appering

**Comment by kevinpapst** [comment]
Check the generated assets to see if the absolute path is still inside.
If you want to change th build, you should do it as it is done in the demo app (see link in readme).

**Comment by Gonzalo1987** [comment]
In the demo app I only can see an root instalation:
https://github.com/kevinpapst/AdminLTEBundle-Demo/blob/master/webpack.config.js

I still have the same problems, my routes are not point to my subdir, I have try all, but nothing works.
