### ISSUE TITLE
Customize AdminLTE

### ISSUE THREAD

**Issue by tooline** [kevinpapst/AdminLTEBundle#93]
how to integrate the following options?
![Sans titre](https://user-images.githubusercontent.com/22789071/67617921-8fe2f580-f7e8-11e9-87a6-3e703881fb1a.png)

Thank you

**Comment by kevinpapst** [comment]
I have no clue what this is

**Comment by tooline** [comment]
I'm ready the template on this link, I find a lot of interesting feature

https://adminlte.io/themes/dev/AdminLTE/index3.html

**Comment by kevinpapst** [comment]
this is adminlte v2, you are talking about v3. You should follow #51

**Comment by tooline** [comment]
thank you for your reply
