### ISSUE TITLE
Update Font Awesome

### ISSUE THREAD

**Issue by Holicz** [kevinpapst/AdminLTEBundle#94]
Currently Font Awesome package is locked on `~5.1.1`. I can't see a reason for being that specific in version number because:

- Font Awesome si not using the third version digit that much
- Font Awesome release minor version (e.g. from 5.1 to 5.2)  approximately once a month
- Font Awesome is not releasing breaking changes in minor versions

I would recommend use something like this `~5.11` which will allow us update the package when the version is lower than `6.0.0`. There is also a possibility to provide something like `~5.11.1` but then we would need release of this package approximately once a month to keep the latest Font Awesome. 

I read the [changelog](https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md) from currently locked version (`5.1.1`) till the current (`5.11.2`) and I can't find a reason to not update it. I will provide a PR since I am personally interested in some new icons.

Thanks for considering it!

**Comment by kevinpapst** [comment]
There is absolutely no reason for locking it down, I guess it was just copy & paste while I added it ;-)
Thanks for the PR!

**Comment by Holicz** [comment]
Thank you for such a fast response! Could you create a release, please?

**Comment by kevinpapst** [comment]
https://github.com/kevinpapst/AdminLTEBundle/releases/tag/3.0.2
