### ISSUE TITLE
Impossible to use form_theme only when needed

### ISSUE THREAD

**Issue by jkabat** [kevinpapst/AdminLTEBundle#96]
Because of mandatory prepend configuration Im not able to turn off form theme where it is not needed:

https://github.com/kevinpapst/AdminLTEBundle/blob/master/DependencyInjection/AdminLTEExtension.php#L115

Is possible to override it somehow?

**Comment by kevinpapst** [comment]
https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/form_theme.md
???

**Comment by jkabat** [comment]
Hmm, yes it is working... Im just wondering if it can be optional, as I want to use this theme only in admin panel, not globally (various frontend templates must always override it). 
From logical point of view I want to setup frontend themes globally and only set admin themes when needed. It certainly not a bug, Im just throwing in a discussion.

**Comment by kevinpapst** [comment]
Hm, okay understand. I guess we can find good arguments for both solutions.
Do you have an idea that does not result in a huge BC break? Removing it will likely break all apps using it currently.

**Comment by jkabat** [comment]
Yes that could work. Maybe somebody has better solution, Im not sure.
Im also thinking about enabling AdminLTE bundle only for admin firewalls, but I did not have time to look at it yet.

**Comment by kevinpapst** [comment]
During the work on AdminLTE 3 I stumbled upon an easy solution for the problem and implemented a single config switch. Check this commit: https://github.com/kevinpapst/AdminLTEBundle/pull/109/commits/7578e117072c7191016391e82cd11034c1d310b9 in PR #109

If you want to back port for the current version, please go ahead!

**Comment by jkabat** [comment]
@kevinpapst Good job!

What are the plans? AdminLTE2 and AdminLTE3 will stay as separate branches? If yes, I will do a back port based on your commit.

**Comment by kevinpapst** [comment]
Eventually AdminLTE 3 will become the master, but there will always be a AdminLTE 2 branch.
I do need AdminLTE for my own project for a longer time until I can migrate, so yes: AdminLTE will stay alive in its own branch.

I should have targeted the commit against the master, but sometimes you realize things too late 😁

**Comment by jkabat** [comment]
yeah, I know that :) can you cherry-pick, or want to do it by me?

**Comment by kevinpapst** [comment]
Cheery-picked into PR #110 
Can you please test if that branch works for you and doesn't introduce a BC break?

**Comment by jkabat** [comment]
@kevinpapst sorry for not testing it yet. I believe I will do that tomorrow or day after that.

**Comment by kevinpapst** [comment]
Kind of "too late" - already merged and released.
But please let me know if it works for you as expected

**Comment by jkabat** [comment]
Thank you @kevinpapst, it works perfectly well!

**Comment by kevinpapst** [comment]
Happy to hear that, then lets move to the next goal: v3
