### ISSUE TITLE
FontAwesome 5: icons are not displayed.

### ISSUE THREAD

**Issue by LaplancheMaxime** [kevinpapst/AdminLTEBundle#99]
Hello, 

After some difficulties I managed to get the template to display. However, the Font awesome icons are not displayed, it displays an unknown character. The library is however well imported into adminlte.css.  

Have you already had the problem? 

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 4.3  |
| AdminLTEBundle  | master/  |
| Operating System  | Mac OS  |

**Comment by kevinpapst** [comment]
Any 404 in your browser console / network tab?
Any browser plugin that might block them?
Using your project in a subdirectory?

**Comment by LaplancheMaxime** [comment]
@kevinpapst yes, I use the project in a subdirectory.. 
My URL project : http://localhost:8888/SUBDIRECTORY/public/index.php/
The 404 URL:
http://localhost:8888/bundles/adminlte/fonts/fa-regular-400.woff2?930c1264
http://localhost:8888/bundles/adminlte/fonts/fa-solid-900.woff?dfc040d5
http://localhost:8888/bundles/adminlte/fonts/fa-regular-400.woff?d9e29124
http://localhost:8888/bundles/adminlte/fonts/fa-regular-400.ttf?cdd8fa76
http://localhost:8888/bundles/adminlte/fonts/fa-solid-900.ttf?a7a790d4

Is there a solution?

**Comment by kevinpapst** [comment]
Yes: https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/frontend_assets.md#subdirectory-usage

**Comment by LaplancheMaxime** [comment]
@kevinpapst Thank you very much, I hadn't seen...

Configuring Webpack.config.js is not easy, but it's all about understanding the trick...
